"use client";
import {PointerLockControls} from "@react-three/drei";
import {useFrame,useThree} from "@react-three/fiber";
import {CapsuleCollider,RigidBody,type RapierRigidBody} from "@react-three/rapier";
import {useEffect,useRef} from "react";
import * as THREE from "three";
import {FLOOR_CONFIG,type Vec3} from "../data/floor8";
function TouchLook(){const {camera,gl}=useThree();useEffect(()=>{let active=false,lastX=0,lastY=0;const el=gl.domElement;const down=(e:PointerEvent)=>{if(e.pointerType!=="mouse"){active=true;lastX=e.clientX;lastY=e.clientY}},move=(e:PointerEvent)=>{if(!active)return;const a=new THREE.Euler(0,0,0,"YXZ");a.setFromQuaternion(camera.quaternion);a.y-=(e.clientX-lastX)*.004;a.x=THREE.MathUtils.clamp(a.x-(e.clientY-lastY)*.004,-1.35,1.35);camera.quaternion.setFromEuler(a);lastX=e.clientX;lastY=e.clientY},up=()=>active=false;el.addEventListener("pointerdown",down);el.addEventListener("pointermove",move);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up);return()=>{el.removeEventListener("pointerdown",down);el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",up);el.removeEventListener("pointercancel",up)}},[camera,gl]);return null}
export function Player({spawn}:{spawn:Vec3}){const body=useRef<RapierRigidBody>(null),keys=useRef<Record<string,boolean>>({}),{camera}=useThree();useEffect(()=>{body.current?.setTranslation({x:spawn[0],y:.85,z:spawn[2]},true);camera.position.set(...spawn);const down=(e:KeyboardEvent)=>keys.current[e.code]=true,up=(e:KeyboardEvent)=>keys.current[e.code]=false;addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[camera,spawn]);useFrame(()=>{const rb=body.current;if(!rb)return;const t=rb.translation(),dir=new THREE.Vector3();camera.getWorldDirection(dir);dir.y=0;dir.normalize();const side=new THREE.Vector3(-dir.z,0,dir.x),move=new THREE.Vector3();if(keys.current.KeyW||keys.current.ArrowUp)move.add(dir);if(keys.current.KeyS||keys.current.ArrowDown)move.sub(dir);if(keys.current.KeyA)move.sub(side);if(keys.current.KeyD)move.add(side);if(move.lengthSq())move.normalize().multiplyScalar(4.2);const v=rb.linvel();rb.setLinvel({x:move.x,y:v.y,z:move.z},true);camera.position.set(t.x,t.y+.85,t.z)});return <><RigidBody ref={body} position={[spawn[0],.85,spawn[2]]} colliders={false} enabledRotations={[false,false,false]} linearDamping={8} canSleep={false}><CapsuleCollider args={[.55,.3]}/></RigidBody><PointerLockControls/><TouchLook/></>}
