"use client";
import { useState } from "react";
import { Building2, Boxes, Footprints, Layers3, Map, Maximize, Menu, Search, X } from "lucide-react";
import { FloorCanvas } from "@/components/floor/FloorCanvas";
import { FloorPlan } from "@/components/floor/FloorPlan";
import { rooms, type Room } from "@/components/floor/floorData";
export type ViewMode = "plan" | "overview" | "walk";
export default function Home(){
 const [mode,setMode]=useState<ViewMode>("overview"),[selected,setSelected]=useState<Room>(rooms[8]),[mobilePanel,setMobilePanel]=useState(false);
 const chooseRoom=(room:Room,open=false)=>{setSelected(room);if(open)setMode("walk");setMobilePanel(false)};
 return <main className="app-shell">
  <aside className={`sidebar ${mobilePanel?"open":""}`}><div className="brand"><span className="brand-mark"><Building2/></span><div><strong>Бинои офисӣ</strong><small>Digital twin · 8 этаж</small></div><button className="mobile-close" onClick={()=>setMobilePanel(false)}><X/></button></div><div className="floor-label">Этажи</div><div className="floor-list">{[10,9,8,7,6,5,4,3,2,1].map(f=><button key={f} className={f===8?"active":""} disabled={f!==8}>{f} этаж</button>)}</div><nav className="nav-modes"><button className={mode==="overview"?"active":""} onClick={()=>{setMode("overview");setMobilePanel(false)}}><Boxes/>3D обзор</button><button className={mode==="plan"?"active":""} onClick={()=>{setMode("plan");setMobilePanel(false)}}><Map/>План этажа</button><button className={mode==="walk"?"active":""} onClick={()=>{setMode("walk");setMobilePanel(false)}}><Footprints/>Прогулка</button></nav></aside>
  <section className="workspace"><header className="topbar"><button className="menu-btn" onClick={()=>setMobilePanel(true)}><Menu/></button><div><b>8 этаж</b><span>+23,700 · архитектурный MVP</span></div><div className="mode-tabs"><button onClick={()=>setMode("plan")} className={mode==="plan"?"active":""}>ПЛАН</button><button onClick={()=>setMode("overview")} className={mode==="overview"?"active":""}>3D ОБЗОР</button><button onClick={()=>setMode("walk")} className={mode==="walk"?"active":""}>ПРОГУЛКА</button></div><button className="round" onClick={()=>document.documentElement.requestFullscreen?.()} title="На весь экран"><Maximize/></button></header><div className="stage">{mode==="plan"?<FloorPlan selectedId={selected.id} onSelect={chooseRoom}/>:<FloorCanvas mode={mode} selected={selected} onSelect={chooseRoom}/>} {mode==="walk"&&<div className="walk-hint"><span>W A S D</span> движение · мышь — обзор · ESC — курсор</div>}</div></section>
  <aside className="details"><div className="details-head"><div><small>ВЫБРАНО</small><h1>{selected.name}</h1><p>8 этаж · {selected.type}</p></div><span className="status">Свободно</span></div><div className="mini-plan"><FloorPlan compact selectedId={selected.id} onSelect={chooseRoom}/></div><div className="metrics"><div><span>Площадь</span><b>≈ {selected.area} м²</b></div><div><span>Высота</span><b>3,0 м</b></div><div><span>ID объекта</span><b>{selected.id}</b></div></div><button className="primary" onClick={()=>setMode("walk")}><Footprints/>Открыть в 3D</button><div className="room-title"><span>Помещения</span><Search/></div><div className="rooms">{rooms.map(r=><button key={r.id} className={selected.id===r.id?"active":""} onClick={()=>chooseRoom(r)}><span>{r.name}<small>{r.type}</small></span><b>{r.area} м²</b></button>)}</div><div className="legend"><Layers3/><span>Геометрия и материалы разделены. Модель готова для следующего этапа дизайна.</span></div></aside>
 </main>
}
