"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {Environment,OrbitControls,PointerLockControls,RoundedBox} from "@react-three/drei";
import {XR,createXRStore} from "@react-three/xr";
import {useEffect,useMemo,useRef,useState} from "react";
import * as THREE from "three";
import {rooms,materialConfig,type Room} from "./floorData";
import type {ViewMode} from "@/app/page";
const xrStore=createXRStore(),rowZ=[-24.5,-17.5,-10.5,-3.5,3.5,10.5,17.5];
const doorZ=[-21.5,-14.5,-7.5,-.5,6.5,13.5,21];
type Box2={minX:number;maxX:number;minZ:number;maxZ:number};
const colliders:Box2[]=[
 {minX:-9.75,maxX:-9.18,minZ:-26.2,maxZ:24.5},{minX:9.18,maxX:9.75,minZ:-26.2,maxZ:24.5},
 {minX:-9.7,maxX:9.7,minZ:-26.25,maxZ:-25.78},
 ...rowZ.flatMap(z=>[{minX:-9.55,maxX:-2.42,minZ:z-.15,maxZ:z+.15},{minX:2.42,maxX:9.55,minZ:z-.15,maxZ:z+.15}]),
 ...[-2.5,2.5].flatMap(x=>{
   const edges=[-25.8,...doorZ.flatMap(z=>[z-.72,z+.72]),23.65];
   const out:Box2[]=[]; for(let i=0;i<edges.length-1;i+=2) out.push({minX:x-.16,maxX:x+.16,minZ:edges[i],maxZ:edges[i+1]}); return out;
 })
];
function Wall({p,s}:{p:[number,number,number],s:[number,number,number]}){return <mesh position={p} castShadow receiveShadow><boxGeometry args={s}/><meshStandardMaterial {...materialConfig.wall}/></mesh>}
function Door({x,z,rot=0}:{x:number;z:number;rot?:number}){return <group position={[x,1.05,z]} rotation-y={rot}><mesh castShadow><boxGeometry args={[1.05,2.1,.09]}/><meshStandardMaterial {...materialConfig.door}/></mesh><mesh position={[-.38,0,.07]}><sphereGeometry args={[.04,10,10]}/><meshStandardMaterial color="#d6ad58" metalness={.7}/></mesh></group>}
function roundedFloorShape(){const s=new THREE.Shape();s.moveTo(-9.5,-28);s.lineTo(9.5,-28);s.lineTo(9.5,24);s.quadraticCurveTo(9.5,28,5.5,28);s.lineTo(-5.5,28);s.quadraticCurveTo(-9.5,28,-9.5,24);s.closePath();return s}
function CorridorWall({x}:{x:number}){return <>{doorZ.map((z,i)=>{const prev=i===0?-25.8:doorZ[i-1]+.72,start=prev,end=z-.72;return <Wall key={`${x}-${z}`} p={[x,1.5,(start+end)/2]} s={[.18,3,end-start]}/>})}<Wall p={[x,1.5,(doorZ.at(-1)!+.72+23.65)/2]} s={[.18,3,23.65-(doorZ.at(-1)!+.72)]}/>{doorZ.map(z=><Door key={`d-${x}-${z}`} x={x} z={z} rot={x<0?-.92:.92}/>)}</>}
function Architecture({selected,onSelect}:{selected:Room;onSelect:(r:Room)=>void}){return <group><mesh rotation-x={-Math.PI/2} receiveShadow><shapeGeometry args={[roundedFloorShape()]}/><meshStandardMaterial {...materialConfig.floor}/></mesh>{rooms.map(r=><mesh key={r.id} rotation-x={-Math.PI/2} position={[r.x,.012,r.z]} onPointerOver={e=>{e.stopPropagation();document.body.style.cursor="pointer"}} onPointerOut={()=>document.body.style.cursor="default"} onClick={e=>{e.stopPropagation();onSelect(r)}}><planeGeometry args={[r.w-.22,r.d-.22]}/><meshStandardMaterial color={selected.id===r.id?materialConfig.selectedFloor.color:"#aeb5bc"} transparent opacity={selected.id===r.id?.72:.38}/></mesh>)}<Wall p={[-9.5,1.5,-1]} s={[.35,3,50]}/><Wall p={[9.5,1.5,-1]} s={[.35,3,50]}/><Wall p={[0,1.5,-26]} s={[19,3,.35]}/>{rowZ.map(z=><group key={z}><Wall p={[-6,1.5,z]} s={[7,3,.18]}/><Wall p={[6,1.5,z]} s={[7,3,.18]}/></group>)}<CorridorWall x={-2.5}/><CorridorWall x={2.5}/><Wall p={[-7.3,1.5,23.5]} s={[4.2,3,.2]}/><Wall p={[7.3,1.5,23.5]} s={[4.2,3,.2]}/>{[-7,-3.5,0,3.5,7].map(x=><mesh key={x} position={[x,1.55,-26.15]}><boxGeometry args={[2.1,1.4,.08]}/><meshStandardMaterial color={materialConfig.window.color} transparent opacity={.42}/></mesh>)}<RoundedBox args={[19,.22,8]} radius={2.2} smoothness={5} position={[0,.1,25]} receiveShadow><meshStandardMaterial color="#9ea6af"/></RoundedBox></group>}
function blocked(p:THREE.Vector3){const radius=.28;return colliders.some(b=>p.x+radius>b.minX&&p.x-radius<b.maxX&&p.z+radius>b.minZ&&p.z-radius<b.maxZ)}
function TouchLook(){const {camera,gl}=useThree();useEffect(()=>{let active=false,lastX=0,lastY=0;const el=gl.domElement;const down=(e:PointerEvent)=>{if(e.pointerType!=="mouse"){active=true;lastX=e.clientX;lastY=e.clientY}};const move=(e:PointerEvent)=>{if(!active)return;const euler=new THREE.Euler(0,0,0,"YXZ");euler.setFromQuaternion(camera.quaternion);euler.y-=(e.clientX-lastX)*.004;euler.x-= (e.clientY-lastY)*.004;euler.x=THREE.MathUtils.clamp(euler.x,-1.35,1.35);camera.quaternion.setFromEuler(euler);lastX=e.clientX;lastY=e.clientY};const up=()=>active=false;el.addEventListener("pointerdown",down);el.addEventListener("pointermove",move);el.addEventListener("pointerup",up);el.addEventListener("pointercancel",up);return()=>{el.removeEventListener("pointerdown",down);el.removeEventListener("pointermove",move);el.removeEventListener("pointerup",up);el.removeEventListener("pointercancel",up)}},[camera,gl]);return null}
function Walker({spawn}:{spawn:[number,number,number]}){const {camera}=useThree(),keys=useRef<Record<string,boolean>>({});useEffect(()=>{camera.position.set(...spawn);camera.lookAt(0,1.7,spawn[2]);const down=(e:KeyboardEvent)=>keys.current[e.code]=true,up=(e:KeyboardEvent)=>keys.current[e.code]=false;addEventListener("keydown",down);addEventListener("keyup",up);return()=>{removeEventListener("keydown",down);removeEventListener("keyup",up)}},[camera,spawn]);useFrame((_,dt)=>{const speed=4.2*Math.min(dt,.05),dir=new THREE.Vector3();camera.getWorldDirection(dir);dir.y=0;dir.normalize();const side=new THREE.Vector3(-dir.z,0,dir.x),delta=new THREE.Vector3();if(keys.current.KeyW||keys.current.ArrowUp)delta.add(dir);if(keys.current.KeyS||keys.current.ArrowDown)delta.sub(dir);if(keys.current.KeyA)delta.sub(side);if(keys.current.KeyD)delta.add(side);if(delta.lengthSq()){delta.normalize().multiplyScalar(speed);const tryX=camera.position.clone();tryX.x+=delta.x;if(!blocked(tryX))camera.position.x=tryX.x;const tryZ=camera.position.clone();tryZ.z+=delta.z;if(!blocked(tryZ))camera.position.z=tryZ.z}camera.position.x=THREE.MathUtils.clamp(camera.position.x,-9.05,9.05);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-25.55,27);camera.position.y=1.7});return <><PointerLockControls/><TouchLook/></>}
function MobilePad(){const press=(code:string,on:boolean)=>window.dispatchEvent(new KeyboardEvent(on?"keydown":"keyup",{code}));return <div className="joystick"><button onPointerDown={()=>press("KeyW",true)} onPointerUp={()=>press("KeyW",false)}>▲</button><div><button onPointerDown={()=>press("KeyA",true)} onPointerUp={()=>press("KeyA",false)}>◀</button><button onPointerDown={()=>press("KeyS",true)} onPointerUp={()=>press("KeyS",false)}>▼</button><button onPointerDown={()=>press("KeyD",true)} onPointerUp={()=>press("KeyD",false)}>▶</button></div></div>}
export function FloorCanvas({mode,selected,onSelect}:{mode:ViewMode;selected:Room;onSelect:(r:Room)=>void}){const [vr,setVr]=useState(false),spawn=useMemo(()=>selected.cameraSpawn,[selected]);useEffect(()=>{navigator.xr?.isSessionSupported("immersive-vr").then(setVr).catch(()=>setVr(false))},[]);return <><Canvas shadows camera={{position:mode==="walk"?spawn:[25,34,38],fov:52}} gl={{antialias:true}}><XR store={xrStore}><color attach="background" args={["#233144"]}/><fog attach="fog" args={["#233144",65,120]}/><ambientLight intensity={1.15}/><directionalLight position={[12,28,8]} intensity={2.4} castShadow shadow-mapSize={[2048,2048]}/><Architecture selected={selected} onSelect={onSelect}/>{mode==="walk"?<Walker spawn={spawn}/>:<OrbitControls makeDefault target={[0,0,0]} minDistance={18} maxDistance={85} maxPolarAngle={1.46}/>}<Environment preset="city"/></XR></Canvas>{mode==="walk"&&<MobilePad/>}<button className={`vr-button ${vr?"supported":""}`} onClick={()=>vr&&xrStore.enterVR()} disabled={!vr}>{vr?"Войти в VR":"VR недоступен"}</button></>}
